import type { Venue } from "./types"

/**
 * 22 reálných ověřených svatebních míst
 * Synchronizuj se supabase/seed-real-venues.sql
 */
export const SAMPLE_VENUES: Venue[] = [
  {
    id: "kvitkuv-dvur", slug: "kvitkuv-dvur",
    title: "Kvítkův Dvůr",
    description: "Zámecký statek dříve součástí areálu zámku Český Krumlov. Unikátní rokokový sál a kabinet, ideální pro intimní svatby s možností vlastního cateringu i pití bez poplatků.",
    location: "od Českých Budějovic, Jihočeský kraj",
    region: "Jihočeský", type: "Zámek",
    capacity: 60, priceFrom: 78000,
    services: ["Vlastní catering bez poplatků", "Catering na vyžádání", "Hostina", "Obřad", "Party"],
    images: [
      "https://images.unsplash.com/photo-1519167758481-83f550bb49b3?w=1600&q=85",
      "https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?w=1600&q=85",
    ],
    features: [
      "Unikátní rokokový sál", "Rokokový kabinet pro přípravu nevěsty",
      "Rybníček", "Repliky celozlacených rokokových příborů Solingen",
      "Luxusní příbory Toner classic prestige", "Bez nočního klidu",
    ],
    isFeatured: true, createdAt: "",
    websiteUrl: "https://www.npu.cz/cs/hrady-a-zamky/tipy-na-vylet/92928-statek-kvitkuv-dvur",
    contactEmail: "kvitkuv.dvur@seznam.cz",
    nearestCity: "České Budějovice", accommodationCapacity: 15,
    cateringPolicy: "own_free", nightPartyPolicy: "no_curfew",
    avgWeddingCost: 150000,
  },
  {
    id: "zamecek-dubi", slug: "zamecek-dubi",
    title: "Zámeček Dubí",
    description: "Lovecký zámeček přírodního typu nedaleko Prahy. Vše na jednom místě s velkorysým ubytováním, obrovskou zahradou a výzdobou v ceně.",
    location: "Dubí, Ústecký kraj — do 100 min od Prahy",
    region: "Ústecký", type: "Zámek",
    capacity: 100, priceFrom: 76000,
    services: ["Vše na jednom místě", "Catering", "Vlastní pití bez poplatků", "Ubytování"],
    images: [
      "https://images.unsplash.com/photo-1519741497674-611481863552?w=1600&q=85",
      "https://images.unsplash.com/photo-1505932794465-147d1f1b2c97?w=1600&q=85",
    ],
    features: ["Obrovská zahrada", "Výzdoba i nábytek v ceně", "Bez nočního klidu", "Lovecký styl"],
    isFeatured: true, createdAt: "",
    websiteUrl: "https://zamecek-dubi.cz",
    contactEmail: "zamecek@profiters.cz",
    nearestCity: "Praha", accommodationCapacity: 60,
    cateringPolicy: "own_drinks_free", nightPartyPolicy: "no_curfew",
    avgWeddingCost: 230000,
  },
  {
    id: "penzion-tereza", slug: "penzion-tereza",
    title: "Penzion Tereza",
    description: "Horský penzion na sjezdovce. Vše na jednom místě, výzdoba v ceně, party místnost pro nerušený provoz po 22:00.",
    location: "Ústecký kraj — do 80 min od Prahy",
    region: "Ústecký", type: "Hotel",
    capacity: 80, priceFrom: 58000,
    services: ["Vše na jednom místě", "Catering od nás", "Pití od nás", "Ubytování"],
    images: [
      "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=1600&q=85",
      "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=1600&q=85",
    ],
    features: ["Penzion na sjezdovce", "Výzdoba v ceně", "Party místnost po 22:00"],
    isFeatured: false, createdAt: "",
    websiteUrl: "https://www.penzion-tereza.cz/",
    contactEmail: "penzion-tereza@profiters.cz",
    nearestCity: "Praha", accommodationCapacity: 50,
    cateringPolicy: "only_venue", nightPartyPolicy: "indoor_after_22",
    avgWeddingCost: 180000,
  },
  {
    id: "stara-posta-varvazov", slug: "stara-posta-varvazov",
    title: "Penzion Stará pošta Varvažov",
    description: "Historický statek s nádhernou zahradou a stodolou. Komplexní servis, ubytování pro 50 hostů, party místnost.",
    location: "Varvažov, Ústecký kraj — do 80 min od Prahy",
    region: "Ústecký", type: "Venkovský statek",
    capacity: 80, priceFrom: 58000,
    services: ["Vše na jednom místě", "Catering od nás", "Pití od nás", "Ubytování"],
    images: [
      "https://images.unsplash.com/photo-1505932794465-147d1f1b2c97?w=1600&q=85",
      "https://images.unsplash.com/photo-1469371670807-013ccf25f16a?w=1600&q=85",
    ],
    features: ["Nádherná zahrada", "Historická stodola", "Party místnost po 22:00"],
    isFeatured: false, createdAt: "",
    websiteUrl: "https://www.pensionstaraposta.cz/",
    contactEmail: "info@profiters.cz",
    nearestCity: "Praha", accommodationCapacity: 50,
    cateringPolicy: "only_venue", nightPartyPolicy: "indoor_after_22",
    avgWeddingCost: 180000,
  },
  {
    id: "apartmany-ralsko", slug: "apartmany-ralsko",
    title: "Apartmány Ralsko",
    description: "Přírodní neokoukané místo v naprosté samotě. Biotop na koupání, vlastní jídlo a pití bez poplatků, žádný noční klid.",
    location: "Ralsko, Liberecký kraj — do 80 min od Prahy",
    region: "Liberecký", type: "Pláž / Příroda",
    capacity: 80, priceFrom: 139000,
    services: ["Vše na jednom místě", "Vlastní jídlo a pití bez poplatků", "Ubytování"],
    images: [
      "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=1600&q=85",
      "https://images.unsplash.com/photo-1606216794074-735e91aa2c92?w=1600&q=85",
    ],
    features: ["Totální samota", "Biotop na koupání", "Žádný noční klid", "Příroda"],
    isFeatured: true, createdAt: "",
    websiteUrl: "https://apartmanyralsko.cz/",
    contactEmail: "apartmanyralsko@svatebnimista.cz",
    nearestCity: "Praha", accommodationCapacity: 45,
    cateringPolicy: "own_free", nightPartyPolicy: "no_curfew",
    avgWeddingCost: 139000,
  },
  {
    id: "fara-pod-milesovkou", slug: "fara-pod-milesovkou",
    title: "Fara pod Milešovkou",
    description: "Moderně zrekonstruovaná fara s industriální prosklenou stodolou. Vkusné pokoje, moderní pojetí historie, vlastní jídlo a pití bez poplatků.",
    location: "Milešovka, Ústecký kraj — do 80 min od Prahy",
    region: "Ústecký", type: "Historická budova",
    capacity: 80, priceFrom: 89000,
    services: ["Vše na jednom místě", "Vlastní jídlo a pití bez poplatků", "Ubytování"],
    images: [
      "https://images.unsplash.com/photo-1469371670807-013ccf25f16a?w=1600&q=85",
      "https://images.unsplash.com/photo-1583939003579-730e3918a45a?w=1600&q=85",
    ],
    features: ["Moderní pojetí historie", "Prosklená stodola", "Vkusné pokoje", "Žádný noční klid"],
    isFeatured: true, createdAt: "",
    websiteUrl: "https://www.farapodmilesovkou.cz/cs/",
    contactEmail: "farapodmilesovkou@svatebnimista.cz",
    nearestCity: "Praha", accommodationCapacity: 20,
    cateringPolicy: "own_free", nightPartyPolicy: "no_curfew",
    avgWeddingCost: 89000,
  },
  {
    id: "zamek-cekanice", slug: "zamek-cekanice",
    title: "Zámek Čekanice",
    description: "Kompaktní zámecká svatba pro menší skupinu. Vlastní jídlo a pití bez poplatků, klidná noc bez omezení.",
    location: "Čekanice, Středočeský kraj — do Prahy",
    region: "Středočeský", type: "Zámek",
    capacity: 70, priceFrom: 50000,
    services: ["Vše na jednom místě", "Vlastní jídlo a pití bez poplatků", "Ubytování"],
    images: [
      "https://images.unsplash.com/photo-1519741497674-611481863552?w=1600&q=85",
      "https://images.unsplash.com/photo-1465495976277-4387d4b0b4c6?w=1600&q=85",
    ],
    features: ["Zámecké prostředí", "Žádný noční klid", "Vlastní catering povolen"],
    isFeatured: false, createdAt: "",
    websiteUrl: "https://www.zamekcekanice.cz/",
    nearestCity: "Praha", accommodationCapacity: 25,
    cateringPolicy: "own_free", nightPartyPolicy: "no_curfew",
    avgWeddingCost: 50000,
  },
  {
    id: "vitovsky-statek", slug: "vitovsky-statek",
    title: "Vítovský Statek",
    description: "Tradiční venkovský statek poblíž Prahy. Komplexní servis včetně cateringu, party místnost po 22:00.",
    location: "Středočeský kraj — do Prahy",
    region: "Středočeský", type: "Venkovský statek",
    capacity: 100, priceFrom: 100000,
    services: ["Vše na jednom místě", "Catering od nás", "Pití od nás", "Ubytování"],
    images: [
      "https://images.unsplash.com/photo-1505932794465-147d1f1b2c97?w=1600&q=85",
      "https://images.unsplash.com/photo-1469371670807-013ccf25f16a?w=1600&q=85",
    ],
    features: ["Statkové prostředí", "Party místnost po 22:00"],
    isFeatured: false, createdAt: "",
    websiteUrl: "https://www.vitovskystatek.cz/",
    nearestCity: "Praha", accommodationCapacity: 20,
    cateringPolicy: "only_venue", nightPartyPolicy: "indoor_after_22",
    avgWeddingCost: 250000,
  },
  {
    id: "panstvi-bzi", slug: "panstvi-bzi",
    title: "Panství Bzí",
    description: "Velkokapacitní statek pro velké svatby až 300 hostů. Vlastní jídlo a pití bez poplatků, ubytování pro 80 hostů.",
    location: "Bzí, Jihočeský kraj — od Českých Budějovic",
    region: "Jihočeský", type: "Venkovský statek",
    capacity: 300, priceFrom: 150000,
    services: ["Vše na jednom místě", "Vlastní jídlo a pití bez poplatků", "Ubytování"],
    images: [
      "https://images.unsplash.com/photo-1505932794465-147d1f1b2c97?w=1600&q=85",
      "https://images.unsplash.com/photo-1606216794074-735e91aa2c92?w=1600&q=85",
    ],
    features: ["Velkokapacitní (až 300)", "Žádný noční klid", "Velké ubytování (80 lůžek)"],
    isFeatured: true, createdAt: "",
    websiteUrl: "https://www.panstvi-bzi.cz/",
    nearestCity: "České Budějovice", accommodationCapacity: 80,
    cateringPolicy: "own_free", nightPartyPolicy: "no_curfew",
    avgWeddingCost: 200000,
  },
  {
    id: "statek-u-kaplicky", slug: "statek-u-kaplicky",
    title: "Statek u Kapličky",
    description: "Romantický venkovský statek s kapličkou. Vše na jednom místě s úplným servisem.",
    location: "Středočeský kraj — do Prahy",
    region: "Středočeský", type: "Venkovský statek",
    capacity: 100, priceFrom: 100000,
    services: ["Vše na jednom místě", "Catering od nás", "Pití od nás", "Ubytování"],
    images: [
      "https://images.unsplash.com/photo-1505932794465-147d1f1b2c97?w=1600&q=85",
      "https://images.unsplash.com/photo-1532712938310-34cb3982ef74?w=1600&q=85",
    ],
    features: ["Romantická kaplička", "Party místnost po 22:00"],
    isFeatured: false, createdAt: "",
    websiteUrl: "https://statek-ukaplicky.cz/",
    nearestCity: "Praha", accommodationCapacity: 20,
    cateringPolicy: "only_venue", nightPartyPolicy: "indoor_after_22",
    avgWeddingCost: 250000,
  },
  {
    id: "stablovice", slug: "zamecky-resort-stablovice",
    title: "Zámecký resort Štáblovice",
    description: "Zámecký resort s francouzskou zahradou pro luxusní obřad. Vše na jednom místě.",
    location: "Štáblovice, Olomoucký kraj — od Olomouce",
    region: "Olomoucký", type: "Zámek",
    capacity: 100, priceFrom: 75000,
    services: ["Vše na jednom místě", "Catering od nás", "Pití od nás", "Ubytování"],
    images: [
      "https://images.unsplash.com/photo-1519741497674-611481863552?w=1600&q=85",
      "https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?w=1600&q=85",
    ],
    features: ["Francouzská zahrada", "Luxusní obřad venku", "Party místnost po 22:00"],
    isFeatured: true, createdAt: "",
    websiteUrl: "https://www.stablovice.cz/svatby/",
    nearestCity: "Olomouc", accommodationCapacity: 20,
    cateringPolicy: "only_venue", nightPartyPolicy: "indoor_after_22",
    avgWeddingCost: 150000,
  },
  {
    id: "hotel-garden-uholubu", slug: "hotel-garden-uholubu",
    title: "Hotel Garden U Holubů",
    description: "Nádherné místo v přírodě v Beskydech — luxus spojený s přírodou. Obřadní místo s výhledem na hory.",
    location: "Beskydy, Moravskoslezský kraj — od Ostravy",
    region: "Moravskoslezský", type: "Hotel",
    capacity: 100, priceFrom: 80000,
    services: ["Vše na jednom místě", "Catering od nás", "Pití od nás", "Ubytování"],
    images: [
      "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=1600&q=85",
      "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=1600&q=85",
    ],
    features: ["Beskydská příroda", "Obřadní místo s výhledem na hory", "Žádný noční klid"],
    isFeatured: true, createdAt: "",
    websiteUrl: "https://www.uholubu.com/",
    nearestCity: "Ostrava", accommodationCapacity: 50,
    cateringPolicy: "only_venue", nightPartyPolicy: "no_curfew",
    avgWeddingCost: 200000,
  },
  {
    id: "victoria-garden", slug: "victoria-garden",
    title: "Victoria Garden",
    description: "Místo inspirované Francií — majitelka dlouhodobě žije ve Francii. Luxusní ubytování ve francouzském duchu.",
    location: "Středočeský kraj — do Prahy",
    region: "Středočeský", type: "Moderní prostor",
    capacity: 80, priceFrom: 90000,
    services: ["Vše na jednom místě", "Vlastní pití bez poplatků", "Ubytování"],
    images: [
      "https://images.unsplash.com/photo-1465495976277-4387d4b0b4c6?w=1600&q=85",
      "https://images.unsplash.com/photo-1532712938310-34cb3982ef74?w=1600&q=85",
    ],
    features: ["Francouzská inspirace", "Luxusní ubytování", "Party místnost po 22:00"],
    isFeatured: true, createdAt: "",
    websiteUrl: "https://www.victoriagarden.cz/",
    nearestCity: "Praha", accommodationCapacity: 32,
    cateringPolicy: "own_drinks_free", nightPartyPolicy: "indoor_after_22",
    avgWeddingCost: 90000,
  },
  {
    id: "capi-hnizdo", slug: "capi-hnizdo",
    title: "Čapí Hnízdo",
    description: "Nádherné přírodní místo s unikátním prostorem pro hostinu v čapím hnízdě. Luxusní ubytování a wellness.",
    location: "Středočeský kraj — do Prahy",
    region: "Středočeský", type: "Hotel",
    capacity: 200, priceFrom: 150000,
    services: ["Vše na jednom místě", "Catering od nás", "Pití od nás", "Ubytování", "Wellness"],
    images: [
      "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=1600&q=85",
      "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=1600&q=85",
    ],
    features: ["Unikátní hostina v čapím hnízdě", "Luxusní wellness", "Velkokapacitní ubytování", "Žádný noční klid"],
    isFeatured: true, createdAt: "",
    websiteUrl: "https://www.capihnizdo.cz/",
    nearestCity: "Praha", accommodationCapacity: 150,
    cateringPolicy: "only_venue", nightPartyPolicy: "no_curfew",
    avgWeddingCost: 350000,
  },
  {
    id: "stodola-pod-lesem", slug: "stodola-pod-lesem",
    title: "Stodola pod lesem",
    description: "Mlýn, stodola a statek v jihomoravské krajině. Komplexní svatební servis, ubytování v okolí.",
    location: "Jihomoravský kraj — 30 min od Brna",
    region: "Jihomoravský", type: "Venkovský statek",
    capacity: 100, priceFrom: 50000,
    services: ["Vše na jednom místě", "Catering od nás", "Pití od nás"],
    images: [
      "https://images.unsplash.com/photo-1469371670807-013ccf25f16a?w=1600&q=85",
      "https://images.unsplash.com/photo-1505932794465-147d1f1b2c97?w=1600&q=85",
    ],
    features: ["Historický mlýn", "Stodola", "Statek", "Party místnost po 22:00"],
    isFeatured: false, createdAt: "",
    websiteUrl: "https://www.stodolapodlesem.cz/",
    nearestCity: "Brno", accommodationCapacity: 0,
    cateringPolicy: "only_venue", nightPartyPolicy: "indoor_after_22",
    avgWeddingCost: 300000,
  },
  {
    id: "hotel-horni-dvur", slug: "hotel-horni-dvur",
    title: "Hotel Horní dvůr",
    description: "Mlýn, stodola a statek na Vysočině. Pet friendly, rybníky a jezírka, vlastní farma.",
    location: "Vysočina — od Prahy",
    region: "Vysočina", type: "Venkovský statek",
    capacity: 150, priceFrom: 100000,
    services: ["Vše na jednom místě", "Catering od nás", "Pití od nás", "Ubytování"],
    images: [
      "https://images.unsplash.com/photo-1505932794465-147d1f1b2c97?w=1600&q=85",
      "https://images.unsplash.com/photo-1606216794074-735e91aa2c92?w=1600&q=85",
    ],
    features: ["Pet friendly", "Rybníky a jezírka", "Vlastní farma", "Žádný noční klid"],
    isFeatured: false, createdAt: "",
    websiteUrl: "https://www.hotelhornidvur.cz/",
    nearestCity: "Praha", accommodationCapacity: 50,
    cateringPolicy: "only_venue", nightPartyPolicy: "no_curfew",
    avgWeddingCost: 200000,
  },
  {
    id: "smrciny", slug: "smrciny",
    title: "Smrčiny",
    description: "Příroda — louka, les a u vody. Sauna, koupací biotop, pet friendly. Žádné limity na parkování. Vlastní pití bez poplatků.",
    location: "Vysočina — do 90 min od Prahy, Brna a Č. Budějovic",
    region: "Vysočina", type: "Pláž / Příroda",
    capacity: 80, priceFrom: 200000,
    services: ["Vše na jednom místě", "Vlastní jídlo a pití bez poplatků", "Ubytování"],
    images: [
      "https://images.unsplash.com/photo-1606216794074-735e91aa2c92?w=1600&q=85",
      "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=1600&q=85",
    ],
    features: [
      "Sauna", "Velký koupací biotop", "Pet friendly bez limitu",
      "Volné parkování", "Krásná moderní stodola", "Bez příplatků za nic", "Žádný noční klid",
    ],
    isFeatured: true, createdAt: "",
    websiteUrl: "https://www.smrciny.com/",
    nearestCity: "Praha", accommodationCapacity: 50,
    cateringPolicy: "own_free", nightPartyPolicy: "no_curfew",
    avgWeddingCost: 500000,
  },
  {
    id: "baresuv-ranc", slug: "baresuv-ranc",
    title: "Barešův Ranč",
    description: "Příroda u rybníku v Královéhradeckém kraji. V létě bazén, lukostřelba, koně. Restaurace přímo u rybníku.",
    location: "Královéhradecký kraj — od Hradce Králové",
    region: "Královéhradecký", type: "Pláž / Příroda",
    capacity: 60, priceFrom: 100000,
    services: ["Vše na jednom místě", "Catering dle domluvy", "Ubytování"],
    images: [
      "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=1600&q=85",
      "https://images.unsplash.com/photo-1525772764200-be829a350797?w=1600&q=85",
    ],
    features: ["Bazén (červen–srpen)", "Restaurace u rybníku", "Lukostřelba", "Koně", "Žádný noční klid"],
    isFeatured: false, createdAt: "",
    websiteUrl: "https://baresuvranc.cz/",
    nearestCity: "Hradec Králové", accommodationCapacity: 50,
    cateringPolicy: "negotiable", nightPartyPolicy: "no_curfew",
    avgWeddingCost: 200000,
  },
  {
    id: "hotel-racek", slug: "hotel-racek",
    title: "Hotel Racek",
    description: "Příroda u vody s luxusním ubytováním v několika různých stylech. Velkokapacitní ubytování pro 100 hostů.",
    location: "Ústecký kraj — do Prahy",
    region: "Ústecký", type: "Pláž / Příroda",
    capacity: 100, priceFrom: 109000,
    services: ["Vše na jednom místě", "Catering od nás", "Pití od nás", "Ubytování"],
    images: [
      "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=1600&q=85",
      "https://images.unsplash.com/photo-1606216794074-735e91aa2c92?w=1600&q=85",
    ],
    features: ["Luxusní ubytování v různých stylech", "U vody", "Party místnost po 22:00"],
    isFeatured: false, createdAt: "",
    websiteUrl: "https://racekhotel.cz/",
    nearestCity: "Praha", accommodationCapacity: 100,
    cateringPolicy: "only_venue", nightPartyPolicy: "indoor_after_22",
    avgWeddingCost: 250000,
  },
  {
    id: "resort-oblik", slug: "resort-oblik",
    title: "Resort Oblík",
    description: "Luxusní statek na samotě s kapacitou 200 hostů. Komplexní servis, ubytování pro 100 lidí.",
    location: "Ústecký kraj — do Prahy",
    region: "Ústecký", type: "Venkovský statek",
    capacity: 200, priceFrom: 150000,
    services: ["Vše na jednom místě", "Catering od nás", "Pití od nás", "Ubytování"],
    images: [
      "https://images.unsplash.com/photo-1505932794465-147d1f1b2c97?w=1600&q=85",
      "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=1600&q=85",
    ],
    features: ["Luxusní statek na samotě", "Velkokapacitní (až 200)", "Žádný noční klid"],
    isFeatured: true, createdAt: "",
    websiteUrl: "https://www.oblik-resort.com/",
    nearestCity: "Praha", accommodationCapacity: 100,
    cateringPolicy: "only_venue", nightPartyPolicy: "no_curfew",
    avgWeddingCost: 500000,
  },
  {
    id: "villa-bork", slug: "villa-bork",
    title: "Villa Bork",
    description: "Luxusní klášter v přírodě (Slovensko). Komplexní servis, dotaz na ceník.",
    location: "Slovensko — od Ostravy",
    region: "Slovensko", type: "Historická budova",
    capacity: 100, priceFrom: 150000,
    services: ["Vše na jednom místě", "Catering od nás", "Pití od nás", "Ubytování"],
    images: [
      "https://images.unsplash.com/photo-1469371670807-013ccf25f16a?w=1600&q=85",
      "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=1600&q=85",
    ],
    features: ["Luxusní klášter", "V přírodě", "Žádný noční klid"],
    isFeatured: false, createdAt: "",
    websiteUrl: "https://www.villabork.sk/",
    nearestCity: "Ostrava", accommodationCapacity: 100,
    cateringPolicy: "only_venue", nightPartyPolicy: "no_curfew",
    avgWeddingCost: 0,
  },
  {
    id: "srub-jezkovec", slug: "srub-jezkovec",
    title: "Srub Ježkovec",
    description: "Dřevěný srub na samotě u lesa na Vysočině. Intimní svatba ve výrazně rustikálním prostředí.",
    location: "Vysočina — do Prahy",
    region: "Vysočina", type: "Pláž / Příroda",
    capacity: 100, priceFrom: 80000,
    services: ["Vše na jednom místě", "Catering od nás", "Pití od nás", "Ubytování"],
    images: [
      "https://images.unsplash.com/photo-1469371670807-013ccf25f16a?w=1600&q=85",
      "https://images.unsplash.com/photo-1606216794074-735e91aa2c92?w=1600&q=85",
    ],
    features: ["Dřevěný srub", "Samota u lesa", "Žádný noční klid"],
    isFeatured: false, createdAt: "",
    websiteUrl: "https://salonmadona.cz/svatebni-misto/srub-jezkovec/",
    nearestCity: "Praha", accommodationCapacity: 50,
    cateringPolicy: "only_venue", nightPartyPolicy: "no_curfew",
    avgWeddingCost: 190000,
  },
]
